default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: postgres
development:
  <<: *default
  database: moyasar_db


test:
  <<: *default
  database: moyasar_db


production:
  <<: *default
  database: moyasar_db

